{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "versus-incident.serviceAccountName" . }}
  labels:
    {{- include "versus-incident.labels" . | nindent 4 }}
{{- end }}
