name: versus
host: 0.0.0.0
port: 3000

alert:
  slack:
    enable: ${SLACK_ENABLE}
    token: ${SLACK_TOKEN}
    channel_id: ${SLACK_CHANNEL_ID}
    template_path: "config/slack_message.tmpl"
  
  telegram:
    enable: ${TELEGRAM_ENABLE}
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}
    template_path: "config/telegram_message.tmpl"