name: versus
host: 0.0.0.0
port: 3000

alert:
  slack:
    enable: false
    token: ${SLACK_TOKEN}
    channel_id: ${SLACK_CHANNEL_ID}
    template_path: "config/slack_message.tmpl"
  
  telegram:
    enable: false
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}
    template_path: "config/telegram_message.tmpl"

queue:
  enable: true
  # AWS SNS
  sns:
    enable: false
  # AWS SQS
  sqs:
    enable: false
    queue_url: your_sqs_queue_url
  # GCP Pub Sub
  pubsub:
    enable: false
  # Azure Event Bus
  azbus:
    enable: false