apiVersion: v2
name: versus-incident
description: A Helm chart for Versus Incident Management System
type: application
version: 1.0.0
appVersion: "1.3.6"

# Dependencies
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
