name: Release Helm Chart as OCI

on:
  push:
    branches:
      - main
    paths:
      - 'helm/versus-incident/**'
      - '.github/workflows/helm-publish.yml'

# Add explicit permissions for the workflow
permissions:
  contents: read
  packages: write    # Needed for publishing to GHCR

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Helm Dependencies
        run: |
          cd helm/versus-incident
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update

      - name: Set version variable
        id: version
        run: |
          VERSION=$(cat helm/versus-incident/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Package and Push Chart to OCI Registry
        run: |
          cd helm/versus-incident
          helm package .
          helm push versus-incident-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository }}/charts
          
      - name: Display installation instructions
        run: |
          echo "Chart published successfully to OCI registry."
          echo "Users can install with: helm install versus-incident oci://ghcr.io/${{ github.repository }}/charts/versus-incident --version ${{ env.VERSION }}